// react-frontend/src/components/categories-section/CategoriesSection.tsx
import { Link } from "react-router";
import type { icategory } from "../../types/category.types";
import { toSlug } from "../../utils/stringUtils";

interface CategoriesSectionProps {
  categories?: icategory[];
}

export default function CategoriesSection({
  categories = [],
}: CategoriesSectionProps) {
  return (
    <section className="section-py bg-warm">
      <div className="container-fluid px-2">
        <div className="text-center mb-5">
          <h2 className="section-title">Choose By Category</h2>
          <p
            className="text-brand-gray mt-2 mx-auto"
            style={{ maxWidth: "520px" }}
          >
            Explore our diverse collection organised by genre and interest
          </p>
        </div>

        <div className="row g-2">
          {categories.map((category, index) => (
            <div
              className={index === 3 ? "col-12 col-md-8" : "col-6 col-md-4"}
              key={category.genreName}
            >
              <Link
                className="category-card d-block text-decoration-none"
                style={{ height: "260px" }}
                to={`/genres/${category.genreId}/${toSlug(category.genreName)}`}
              >
                <img
                  src={category.imgUrl ?? ""}
                  alt={category.genreName}
                  loading="lazy"
                />
                <div className="cat-overlay">
                  <p className="cat-name px-3">{category.genreName}</p>
                  {category.count ? (
                    <small className="text-white-50 mt-1">
                      {category.count} books
                    </small>
                  ) : null}
                </div>
              </Link>
            </div>
          ))}
        </div>

        <div className="text-center mt-5">
          <Link
            to="/genres"
            className="btn btn-gold btn-lg px-5 text-uppercase fw-bold"
          >
            See All Categories
          </Link>
        </div>
      </div>
    </section>
  );
}

// frontEnd/src/app/components/categories-section/categories-section.component.ts
import { Component, Input } from "@angular/core";
import { CommonModule } from "@angular/common";
import { RouterLink } from "@angular/router";
import { icategory } from "../../models/icategory";

@Component({
  selector: "app-categories-section",
  standalone: true,
  imports: [CommonModule, RouterLink],
  templateUrl: "./categories-section.component.html",
})
export class CategoriesSectionComponent {
  @Input() categories: icategory[] = [];

  toSlug(value: string) {
    return value
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "");
  }
}

<section class="section-py bg-warm">
  <div class="container-fluid px-2">
    <div class="text-center mb-5">
      <h2 class="section-title">Choose By Category</h2>
      <p class="text-brand-gray mt-2 mx-auto" style="max-width: 520px">
        Explore our diverse collection organised by genre and interest
      </p>
    </div>

    <div class="row g-2">
      @for (cat of categories; track cat.genreName; let i = $index) {
        <!-- First 3 normal, 4th wide, last 2 normal -->
        <div [class]="i === 3 ? 'col-12 col-md-8' : 'col-6 col-md-4'">
          <a
            class="category-card d-block text-decoration-none"
            style="height: 260px"
            [routerLink]="['/genres', cat.genreId, toSlug(cat.genreName)]"
          >
            <img [src]="cat.imgUrl" [alt]="cat.genreName" loading="lazy" />
            <div class="cat-overlay">
              <p class="cat-name px-3">{{ cat.genreName }}</p>
              @if (cat.count) {
                <small class="text-white-50 mt-1">{{ cat.count }} books</small>
              }
            </div>
          </a>
        </div>
      }
    </div>

    <div class="text-center mt-5">
      <a
        routerLink="/genres"
        class="btn btn-gold btn-lg px-5 text-uppercase fw-bold"
      >
        See All Categories
      </a>
    </div>
  </div>
</section>
