// react-frontend/src/components/admin/admin-topbar/AdminTopbar.tsx
interface AdminTopbarProps {
  topbarTitle: string;
  topbarSub: string;
}

export default function AdminTopbar({
  topbarTitle,
  topbarSub,
}: AdminTopbarProps) {
  return (
    <div className="admin-topbar">
      <div>
        <div className="topbar-title">{topbarTitle}</div>
        <div className="topbar-subtitle">{topbarSub}</div>
      </div>
      <div className="topbar-actions">
        <div className="search-wrap">
          <i className="bi bi-search" />
          <input className="search-input" type="text" placeholder="Search..." />
        </div>
        <div className="icon-btn-admin">
          <i className="bi bi-bell" />
          <div className="notif-dot" />
        </div>
        <div className="icon-btn-admin">
          <i className="bi bi-question-circle" />
        </div>
      </div>
    </div>
  );
}

// frontEnd/src/app/components/admin/admin-topbar/admin-topbar.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-admin-topbar',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './admin-topbar.component.html',
  styleUrl: './admin-topbar.component.scss'
})
export class AdminTopbarComponent {
  @Input() topbarTitle: string = '';
  @Input() topbarSub: string = '';
}

<div class="admin-topbar">
    <div>
        <div class="topbar-title">{{ topbarTitle }}</div>
        <div class="topbar-subtitle">{{ topbarSub }}</div>
    </div>
    <div class="topbar-actions">
        <div class="search-wrap">
            <i class="bi bi-search"></i>
            <input class="search-input" type="text" placeholder="Search...">
        </div>
        <div class="icon-btn-admin"><i class="bi bi-bell"></i>
            <div class="notif-dot"></div>
        </div>
        <div class="icon-btn-admin"><i class="bi bi-question-circle"></i></div>
    </div>
</div>
