// react-frontend/src/components/page-banner/PageBanner.tsx
import { Link } from "react-router-dom";

interface PageBannerProps {
  title: string;
  subtitle?: string;
  showBreadcrumb?: boolean;
}

export default function PageBanner({
  title,
  subtitle = "",
  showBreadcrumb = true,
}: PageBannerProps) {
  return (
    <div className="page-banner">
      <div className="container text-center">
        <h1 className="section-title mb-2">{title}</h1>

        {subtitle && (
          <p
            className="text-brand-gray mb-3"
            style={{ maxWidth: 580, margin: "0 auto" }}
          >
            {subtitle}
          </p>
        )}

        {showBreadcrumb && (
          <nav aria-label="breadcrumb" className="mt-2">
            <ol className="breadcrumb justify-content-center mb-0">
              <li className="breadcrumb-item">
                <Link to="/" className="text-gold">
                  Home
                </Link>
              </li>
              <li className="breadcrumb-item active text-brand-gray">
                {title}
              </li>
            </ol>
          </nav>
        )}
      </div>
    </div>
  );
}

// frontEnd/src/app/components/page-banner/page-banner.component.ts
import { Component, Input } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-page-banner',
  standalone: true,
  imports: [RouterLink],
  template: `
    <div class="page-banner">
      <div class="container text-center">
        <h1 class="section-title mb-2">{{ title }}</h1>
        @if (subtitle) {
          <p class="text-brand-gray mb-3" style="max-width:580px;margin:0 auto">{{ subtitle }}</p>
        }
        @if (showBreadcrumb) {
          <nav aria-label="breadcrumb" class="mt-2">
            <ol class="breadcrumb justify-content-center mb-0">
              <li class="breadcrumb-item">
                <a routerLink="/" class="text-gold">Home</a>
              </li>
              <li class="breadcrumb-item active text-brand-gray">{{ title }}</li>
            </ol>
          </nav>
        }
      </div>
    </div>
  `
})
export class PageBannerComponent {
  @Input() title!: string;
  @Input() subtitle = '';
  @Input() showBreadcrumb = true;
}
