// react-frontend/src/components/address-form-modal/AddressFormModal.tsx
import { useEffect } from "react";
import { useForm } from "react-hook-form";
import { toast } from "sonner";
import * as addressService from "../../services/addressService";
import type {
  IAddress,
  ICreateAddressRequest,
} from "../../types/address.types";
import "./AddressFormModal.css";

// ── props ──────────────────────────────────────────────────────────────────
interface AddressFormModalProps {
  isOpen: boolean;
  address?: IAddress; // present → edit mode
  isFirstAddress?: boolean; // true → pre-fill label=Home, isDefault=true
  onSaved: (address: IAddress) => void;
  onClosed: () => void;
}

// ── component ──────────────────────────────────────────────────────────────
export default function AddressFormModal({
  isOpen,
  address,
  isFirstAddress = false,
  onSaved,
  onClosed,
}: AddressFormModalProps) {
  const isEditMode = !!address;

  const {
    register,
    handleSubmit,
    reset,
    formState: { errors, isSubmitting, isValid },
  } = useForm<ICreateAddressRequest>({
    mode: "onTouched",
    defaultValues: {
      label: "",
      fullName: "",
      phone: "",
      addressLine1: "",
      addressLine2: "",
      city: "",
      state: "",
      postalCode: "",
      country: "",
      isDefault: false,
    },
  });

  // Pre-fill when modal opens
  useEffect(() => {
    if (!isOpen) return;
    if (isEditMode && address) {
      reset(address);
    } else if (isFirstAddress) {
      reset((prev) => ({ ...prev, label: "Home", isDefault: true }));
    } else {
      reset();
    }
  }, [isOpen, address, isEditMode, isFirstAddress, reset]);

  // ── submit ─────────────────────────────────────────────────────────────
  const onSubmit = handleSubmit(async (formData) => {
    if (isEditMode && address) {
      try {
        await addressService.updateAddress(address.addressId, formData);
        const updated: IAddress = { ...address, ...formData };
        toast.success("Address updated successfully");
        onSaved(updated);
        close();
      } catch {
        toast.error("Failed to update address");
      }
    } else {
      try {
        const res = await addressService.createAddress(formData);
        const created: IAddress = {
          addressId: res.data.addressId,
          ...formData,
        };
        toast.success("Address saved successfully");
        onSaved(created);
        close();
      } catch {
        toast.error("Failed to save address");
      }
    }
  });

  const close = () => {
    reset();
    onClosed();
  };

  const onBackdropClick = (e: React.MouseEvent<HTMLDivElement>) => {
    if ((e.target as HTMLElement).classList.contains("modal-backdrop")) {
      close();
    }
  };

  // ── render ─────────────────────────────────────────────────────────────
  if (!isOpen) return null;

  return (
    <div className="modal-backdrop" onClick={onBackdropClick}>
      <div className="modal-dialog" onClick={(e) => e.stopPropagation()}>
        {/* Header */}
        <div className="modal-header">
          <h5 className="modal-title">
            <i className={`bi ${isEditMode ? "bi-pencil" : "bi-plus-lg"}`} />
            {isEditMode ? "Edit Address" : "Add New Address"}
          </h5>
          <button type="button" className="btn-close-modal" onClick={close}>
            <i className="bi bi-x-lg" />
          </button>
        </div>

        {/* Body */}
        <form onSubmit={onSubmit} noValidate>
          <div className="modal-body">
            {/* Label */}
            <div className="form-group">
              <label className="form-label-sm">Label</label>
              <input
                type="text"
                className="form-control-custom"
                placeholder="e.g. Home, Office"
                {...register("label", { required: true, maxLength: 50 })}
              />
              {errors.label && (
                <div className="field-error">
                  Label is required (max 50 characters)
                </div>
              )}
            </div>

            {/* Full Name + Phone */}
            <div className="row g-3">
              <div className="col-md-6">
                <div className="form-group">
                  <label className="form-label-sm">Full Name</label>
                  <input
                    type="text"
                    className="form-control-custom"
                    placeholder="John Doe"
                    {...register("fullName", {
                      required: true,
                      maxLength: 150,
                    })}
                  />
                  {errors.fullName && (
                    <div className="field-error">Full name is required</div>
                  )}
                </div>
              </div>
              <div className="col-md-6">
                <div className="form-group">
                  <label className="form-label-sm">Phone</label>
                  <input
                    type="tel"
                    className="form-control-custom"
                    placeholder="+20 1234567890"
                    {...register("phone", { required: true, maxLength: 30 })}
                  />
                  {errors.phone && (
                    <div className="field-error">Phone is required</div>
                  )}
                </div>
              </div>
            </div>

            {/* Address Line 1 */}
            <div className="form-group">
              <label className="form-label-sm">Address Line 1</label>
              <input
                type="text"
                className="form-control-custom"
                placeholder="Street address"
                {...register("addressLine1", {
                  required: true,
                  maxLength: 250,
                })}
              />
              {errors.addressLine1 && (
                <div className="field-error">Address is required</div>
              )}
            </div>

            {/* Address Line 2 */}
            <div className="form-group">
              <label className="form-label-sm">Address Line 2 (Optional)</label>
              <input
                type="text"
                className="form-control-custom"
                placeholder="Apartment, suite, floor"
                {...register("addressLine2", { maxLength: 250 })}
              />
            </div>

            {/* City + State */}
            <div className="row g-3">
              <div className="col-md-6">
                <div className="form-group">
                  <label className="form-label-sm">City</label>
                  <input
                    type="text"
                    className="form-control-custom"
                    placeholder="Cairo"
                    {...register("city", { required: true, maxLength: 100 })}
                  />
                  {errors.city && (
                    <div className="field-error">City is required</div>
                  )}
                </div>
              </div>
              <div className="col-md-6">
                <div className="form-group">
                  <label className="form-label-sm">State (Optional)</label>
                  <input
                    type="text"
                    className="form-control-custom"
                    placeholder="e.g. Cairo Governorate"
                    {...register("state", { maxLength: 100 })}
                  />
                </div>
              </div>
            </div>

            {/* Postal Code + Country */}
            <div className="row g-3">
              <div className="col-md-6">
                <div className="form-group">
                  <label className="form-label-sm">Postal Code</label>
                  <input
                    type="text"
                    className="form-control-custom"
                    placeholder="11511"
                    {...register("postalCode", {
                      required: true,
                      maxLength: 20,
                    })}
                  />
                  {errors.postalCode && (
                    <div className="field-error">Postal code is required</div>
                  )}
                </div>
              </div>
              <div className="col-md-6">
                <div className="form-group">
                  <label className="form-label-sm">Country Code</label>
                  <input
                    type="text"
                    className="form-control-custom"
                    placeholder="EG"
                    maxLength={2}
                    style={{ textTransform: "uppercase" }}
                    {...register("country", {
                      required: true,
                      minLength: 2,
                      maxLength: 2,
                    })}
                  />
                  {errors.country && (
                    <div className="field-error">
                      2-letter country code required
                    </div>
                  )}
                </div>
              </div>
            </div>

            {/* Default Checkbox */}
            <div className="default-check">
              <label className="check-label">
                <input type="checkbox" {...register("isDefault")} />
                <span>Set as default shipping address</span>
              </label>
            </div>
          </div>

          {/* Footer */}
          <div className="modal-footer">
            <button type="button" className="btn-outline-cust" onClick={close}>
              Cancel
            </button>
            <button
              type="submit"
              className="btn-gold-cust d-flex align-items-center gap-2"
              disabled={!isValid || isSubmitting}
            >
              {isSubmitting ? (
                <span
                  className="spinner-border spinner-border-sm"
                  role="status"
                />
              ) : (
                <i className="bi bi-check2" />
              )}
              {isEditMode ? "Save Changes" : "Save Address"}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}

// frontEnd/src/app/components/address-form-modal/address-form-modal.component.ts
import {
  Component,
  EventEmitter,
  inject,
  Input,
  OnInit,
  Output,
} from "@angular/core";
import { CommonModule } from "@angular/common";
import {
  ReactiveFormsModule,
  FormBuilder,
  FormGroup,
  Validators,
} from "@angular/forms";
import { IAddress } from "../../models/Address/iaddress";
import { ICreateAddressRequest } from "../../models/Address/icreate-address-request";
import { ApiAddressService } from "../../services/addresses/api-address.service";
import { ToastService } from "../../services/toast.service";

@Component({
  selector: "app-address-form-modal",
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule],
  templateUrl: "./address-form-modal.component.html",
  styleUrl: "./address-form-modal.component.scss",
})
export class AddressFormModalComponent implements OnInit {
  /** Pass an existing address to enter edit mode. Null = create mode. */
  @Input() address?: IAddress;

  /** When true, pre-fills label='Home' and isDefault=true (for first-ever address). */
  @Input() isFirstAddress = false;

  /** Whether the modal is visible. */
  @Input() isOpen = false;

  /** Emits the saved address (created or updated) so the parent can update its list. */
  @Output() saved = new EventEmitter<IAddress>();

  /** Emits when the modal is closed without saving. */
  @Output() closed = new EventEmitter<void>();

  addressForm: FormGroup;
  isSubmitting = false;

  private fb = inject(FormBuilder);
  private addressService = inject(ApiAddressService);
  private toastService = inject(ToastService);

  get isEditMode(): boolean {
    return !!this.address;
  }

  constructor() {
    this.addressForm = this.fb.group({
      label: ["", [Validators.required, Validators.maxLength(50)]],
      fullName: ["", [Validators.required, Validators.maxLength(150)]],
      phone: ["", [Validators.required, Validators.maxLength(30)]],
      addressLine1: ["", [Validators.required, Validators.maxLength(250)]],
      addressLine2: ["", [Validators.maxLength(250)]],
      city: ["", [Validators.required, Validators.maxLength(100)]],
      state: ["", [Validators.maxLength(100)]],
      postalCode: ["", [Validators.required, Validators.maxLength(20)]],
      country: [
        "",
        [
          Validators.required,
          Validators.minLength(2),
          Validators.maxLength(2),
        ],
      ],
      isDefault: [false],
    });
  }

  ngOnInit(): void {
    if (this.isEditMode && this.address) {
      this.addressForm.patchValue(this.address);
    } else if (this.isFirstAddress) {
      this.addressForm.patchValue({ label: "Home", isDefault: true });
    }
  }

  onSubmit(): void {
    if (this.addressForm.invalid) {
      this.addressForm.markAllAsTouched();
      return;
    }

    this.isSubmitting = true;
    const formData: ICreateAddressRequest = this.addressForm.value;

    if (this.isEditMode && this.address) {
      this.addressService
        .update(this.address.addressId, formData)
        .subscribe({
          next: () => {
            const updated: IAddress = {
              ...this.address!,
              ...formData,
            };
            this.toastService.show("Address updated successfully", "success");
            this.saved.emit(updated);
            this.isSubmitting = false;
            this.close();
          },
          error: () => {
            this.toastService.show("Failed to update address", "error");
            this.isSubmitting = false;
          },
        });
    } else {
      this.addressService.create(formData).subscribe({
        next: (result) => {
          const created: IAddress = {
            addressId: result.addressId,
            ...formData,
          };
          this.toastService.show("Address saved successfully", "success");
          this.saved.emit(created);
          this.isSubmitting = false;
          this.close();
        },
        error: () => {
          this.toastService.show("Failed to save address", "error");
          this.isSubmitting = false;
        },
      });
    }
  }

  close(): void {
    this.isOpen = false;
    this.closed.emit();
    this.addressForm.reset();
  }

  /** Close when clicking the backdrop (not the modal content). */
  onBackdropClick(event: MouseEvent): void {
    if ((event.target as HTMLElement).classList.contains("modal-backdrop")) {
      this.close();
    }
  }
}

<div
  class="modal-backdrop"
  *ngIf="isOpen"
  (click)="onBackdropClick($event)"
>
  <div class="modal-dialog" (click)="$event.stopPropagation()">
    <!-- Header -->
    <div class="modal-header">
      <h5 class="modal-title">
        <i class="bi" [ngClass]="isEditMode ? 'bi-pencil' : 'bi-plus-lg'"></i>
        {{ isEditMode ? "Edit Address" : "Add New Address" }}
      </h5>
      <button type="button" class="btn-close-modal" (click)="close()">
        <i class="bi bi-x-lg"></i>
      </button>
    </div>

    <!-- Body -->
    <form [formGroup]="addressForm" (ngSubmit)="onSubmit()">
      <div class="modal-body">
        <!-- Label -->
        <div class="form-group">
          <label class="form-label-sm">Label</label>
          <input
            type="text"
            class="form-control-custom"
            formControlName="label"
            placeholder="e.g. Home, Office"
          />
          <div
            class="field-error"
            *ngIf="
              addressForm.get('label')?.touched &&
              addressForm.get('label')?.invalid
            "
          >
            Label is required (max 50 characters)
          </div>
        </div>

        <!-- Full Name + Phone -->
        <div class="row g-3">
          <div class="col-md-6">
            <div class="form-group">
              <label class="form-label-sm">Full Name</label>
              <input
                type="text"
                class="form-control-custom"
                formControlName="fullName"
                placeholder="John Doe"
              />
              <div
                class="field-error"
                *ngIf="
                  addressForm.get('fullName')?.touched &&
                  addressForm.get('fullName')?.invalid
                "
              >
                Full name is required
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <label class="form-label-sm">Phone</label>
              <input
                type="tel"
                class="form-control-custom"
                formControlName="phone"
                placeholder="+20 1234567890"
              />
              <div
                class="field-error"
                *ngIf="
                  addressForm.get('phone')?.touched &&
                  addressForm.get('phone')?.invalid
                "
              >
                Phone is required
              </div>
            </div>
          </div>
        </div>

        <!-- Address Line 1 -->
        <div class="form-group">
          <label class="form-label-sm">Address Line 1</label>
          <input
            type="text"
            class="form-control-custom"
            formControlName="addressLine1"
            placeholder="Street address"
          />
          <div
            class="field-error"
            *ngIf="
              addressForm.get('addressLine1')?.touched &&
              addressForm.get('addressLine1')?.invalid
            "
          >
            Address is required
          </div>
        </div>

        <!-- Address Line 2 -->
        <div class="form-group">
          <label class="form-label-sm">Address Line 2 (Optional)</label>
          <input
            type="text"
            class="form-control-custom"
            formControlName="addressLine2"
            placeholder="Apartment, suite, floor"
          />
        </div>

        <!-- City + State -->
        <div class="row g-3">
          <div class="col-md-6">
            <div class="form-group">
              <label class="form-label-sm">City</label>
              <input
                type="text"
                class="form-control-custom"
                formControlName="city"
                placeholder="Cairo"
              />
              <div
                class="field-error"
                *ngIf="
                  addressForm.get('city')?.touched &&
                  addressForm.get('city')?.invalid
                "
              >
                City is required
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <label class="form-label-sm">State (Optional)</label>
              <input
                type="text"
                class="form-control-custom"
                formControlName="state"
                placeholder="e.g. Cairo Governorate"
              />
            </div>
          </div>
        </div>

        <!-- Postal Code + Country -->
        <div class="row g-3">
          <div class="col-md-6">
            <div class="form-group">
              <label class="form-label-sm">Postal Code</label>
              <input
                type="text"
                class="form-control-custom"
                formControlName="postalCode"
                placeholder="11511"
              />
              <div
                class="field-error"
                *ngIf="
                  addressForm.get('postalCode')?.touched &&
                  addressForm.get('postalCode')?.invalid
                "
              >
                Postal code is required
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <label class="form-label-sm">Country Code</label>
              <input
                type="text"
                class="form-control-custom"
                formControlName="country"
                placeholder="EG"
                maxlength="2"
                style="text-transform: uppercase"
              />
              <div
                class="field-error"
                *ngIf="
                  addressForm.get('country')?.touched &&
                  addressForm.get('country')?.invalid
                "
              >
                2-letter country code required
              </div>
            </div>
          </div>
        </div>

        <!-- Default Checkbox -->
        <div class="default-check">
          <label class="check-label">
            <input type="checkbox" formControlName="isDefault" />
            <span>Set as default shipping address</span>
          </label>
        </div>
      </div>

      <!-- Footer -->
      <div class="modal-footer">
        <button type="button" class="btn-outline-cust" (click)="close()">
          Cancel
        </button>
        <button
          type="submit"
          class="btn-gold-cust d-flex align-items-center gap-2"
          [disabled]="addressForm.invalid || isSubmitting"
        >
          <span
            *ngIf="isSubmitting"
            class="spinner-border spinner-border-sm"
            role="status"
          ></span>
          <i *ngIf="!isSubmitting" class="bi bi-check2"></i>
          {{ isEditMode ? "Save Changes" : "Save Address" }}
        </button>
      </div>
    </form>
  </div>
</div>
