// frontEnd/src/app/components/header/header.component.ts
import { Component, ViewChild, inject } from "@angular/core";
import { RouterLink, RouterLinkActive, Router } from "@angular/router";
import { FormsModule } from "@angular/forms";
import { CartService } from "../../services/cart.service";
import { ToastService } from "../../services/toast.service";
import { AuthModalComponent } from "../auth-modal/auth-modal.component";
import { ApiUserService } from "../../services/users/api-user.service";
import { ChangePasswordModalComponent } from "../change-password-modal/change-password-modal.component";

@Component({
  selector: "app-header",
  standalone: true,
  imports: [
    RouterLink,
    RouterLinkActive,
    FormsModule,
    AuthModalComponent,
    ChangePasswordModalComponent,
  ],
  templateUrl: "./header.component.html",
})
export class HeaderComponent {
  @ViewChild(AuthModalComponent) authModal?: AuthModalComponent;

  showChangePasswordModal = false;
  navItems = [
    { label: "Genres", path: "/genres" },
    { label: "All Books", path: "/all-books" },
    { label: "New Arrival", path: "/new-arrival" },
    { label: "Featured Books", path: "/featured-books" },
    { label: "Editor's Pick", path: "/editors-pick" },
    { label: "About", path: "/about" },
    { label: "Contact", path: "/contact" },
  ];

  router = inject(Router);
  toastService = inject(ToastService);
  searchQuery = "";

  constructor(
    public cartService: CartService,
    public userService: ApiUserService,
  ) {}

  onSearch() {
    if (this.searchQuery.trim()) {
      this.router.navigate(["/search-results"], {
        queryParams: { search: this.searchQuery },
      });
      this.searchQuery = "";
    }
  }

  onLogin(user: any) {
    this.toastService.show(`Successfully logged in!`, "success");
  }

  openAuthModal(mode: "login" | "signup" = "login") {
    if (mode === "signup") {
      this.authModal?.setSignupMode();
      return;
    }

    this.authModal?.setLoginMode();
  }

  onLogout() {
    this.userService.logout();
    this.cartService.switchToGuestCart();
    this.router.navigate(["/"]);
    this.toastService.show("Successfully logged out", "info");
  }
}

<nav class="navbar navbar-expand-lg main-navbar sticky-top">
  <div class="container">
    <!-- Brand -->
    <a class="navbar-brand d-flex align-items-center gap-2" routerLink="/">
      <div
        class="d-flex align-items-center justify-content-center rounded-2 bg-gold"
        style="width: 38px; height: 38px; flex-shrink: 0"
      >
        <span style="font-size: 1.1rem">📚</span>
      </div>
      <span
        class="fw-bold fs-4"
        style="
          color: var(--brand-dark);
          font-family: &quot;Lato&quot;, sans-serif;
        "
      >
        Book<span class="text-gold">Worms</span>
      </span>
    </a>

    <!-- Mobile toggle -->
    <button
      class="navbar-toggler border-0 p-1"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#mainNav"
      aria-label="Toggle navigation"
    >
      <i
        class="bi bi-list"
        style="font-size: 1.6rem; color: var(--brand-dark)"
      ></i>
    </button>

    <!-- Collapse -->
    <div class="collapse navbar-collapse" id="mainNav">
      <ul class="navbar-nav mx-auto gap-lg-1 py-3 py-lg-0">
        @for (item of navItems; track item.label) {
          <li class="nav-item">
            <a
              class="nav-link"
              [routerLink]="item.path"
              routerLinkActive="active"
            >
              {{ item.label }}
            </a>
          </li>
        }
      </ul>

      <!-- Action icons -->
      <div class="d-flex align-items-center gap-1 mt-2 mt-lg-0">
        <form class="d-flex me-2 position-relative" (ngSubmit)="onSearch()">
          <input
            type="text"
            class="form-control form-control-sm rounded-pill px-3 py-1"
            placeholder="Search books..."
            [(ngModel)]="searchQuery"
            name="search"
            style="border-color: #c78b51; min-width: 160px; font-size: 0.85rem"
          />
          <button
            type="submit"
            class="btn btn-sm position-absolute end-0 top-50 translate-middle-y"
            style="color: #c78b51; border: none; background: transparent"
          >
            <i class="bi bi-search"></i>
          </button>
        </form>
        <button
          class="icon-btn"
          (click)="cartService.toggleCart()"
          aria-label="Cart"
        >
          <i class="bi bi-bag"></i>
          @if (cartService.totalItems() > 0) {
            <span class="cart-pill">{{ cartService.totalItems() }}</span>
          }
        </button>

        @if (!userService.isLoggedIn()) {
          <button
            type="button"
            class="icon-btn"
            aria-label="Account"
            data-bs-toggle="modal"
            data-bs-target="#authModal"
            (click)="openAuthModal('login')"
          >
            <i class="bi bi-person"></i>
          </button>
        } @else {
          <!-- Logged in: Show Dropdown -->
          <div class="dropdown d-inline-block">
            <button
              class="icon-btn dropdown-toggle"
              type="button"
              data-bs-toggle="dropdown"
              aria-expanded="false"
              style="border: none; background: transparent"
            >
              <i class="bi bi-person-check fs-5"></i>
            </button>

            <ul
              class="dropdown-menu dropdown-menu-end mt-2 shadow border-0"
              style="min-width: 200px"
            >
              <!-- Role-based link -->
              @if (userService.userRole() === "Admin") {
                <li>
                  <a class="dropdown-item py-2" routerLink="/admin-dashboard">
                    <i class="bi bi-speedometer2 me-2 text-gold"></i>Admin
                    Dashboard
                  </a>
                </li>
              } @else {
                <li>
                  <a class="dropdown-item py-2" routerLink="/my-account">
                    <i class="bi bi-house-door me-2 text-gold"></i>My Account
                  </a>
                </li>
              }
              <!-- Always show Profile link for logged-in users -->
              <li>
                <a class="dropdown-item py-2" routerLink="/profile">
                  <i class="bi bi-person-circle me-2 text-gold"></i>Profile
                </a>
              </li>
              <li><hr class="dropdown-divider" /></li>
              <li>
                <button
                  class="dropdown-item py-2"
                  (click)="showChangePasswordModal = true"
                >
                  <i class="bi bi-shield-lock me-2 text-gold"></i>Change
                  Password
                </button>
              </li>
              <!-- Logout button -->
              <li>
                <button
                  class="dropdown-item py-2 text-danger"
                  (click)="onLogout()"
                >
                  <i class="bi bi-box-arrow-right me-2"></i>Logout
                </button>
              </li>
            </ul>
          </div>
        }

        <a
          routerLink="/cart"
          class="btn btn-gold btn-sm ms-2 px-3 text-uppercase fw-bold"
          style="letter-spacing: 0.05em; font-size: 0.75rem"
        >
          <i class="bi bi-bag-check me-1"></i>Cart
        </a>
      </div>
    </div>
  </div>
</nav>

<app-auth-modal (loggedIn)="onLogin($event)"></app-auth-modal>
@if (showChangePasswordModal) {
  <app-change-password-modal
    (close)="showChangePasswordModal = false"
  ></app-change-password-modal>
}

// react-frontend/src/components/header/Header.tsx
import { useState, type FormEvent } from "react";
import { Link, NavLink, useNavigate } from "react-router";
import AuthModal from "../auth-modal/AuthModal";
import { useAuthStore } from "../../services/auth/useAuthStore";
import { useCartStore, selectTotalItems } from "../../store/useCartStore";
import { showToast } from "../../utils/toast";
import ChangePasswordModal from "../change-password-modal/ChangePasswordModal";

type AuthMode = "login" | "signup";

const navItems = [
  { label: "Genres", path: "/genres" },
  { label: "All Books", path: "/all-books" },
  { label: "New Arrival", path: "/new-arrival" },
  { label: "Featured Books", path: "/featured-books" },
  { label: "Editor's Pick", path: "/editors-pick" },
  { label: "About", path: "/about" },
];

export default function Header() {
  const [searchQuery, setSearchQuery] = useState("");
  const [isNavOpen, setIsNavOpen] = useState(false);
  const [isUserMenuOpen, setIsUserMenuOpen] = useState(false);
  const [isAuthModalOpen, setIsAuthModalOpen] = useState(false);
  const [authMode, setAuthMode] = useState<AuthMode>("login");
  const navigate = useNavigate();
  const isLoggedIn = useAuthStore((state) => state.isLoggedIn);
  const userRole = useAuthStore((state) => state.userRole);
  const logout = useAuthStore((state) => state.logout);
  const toggleCart = useCartStore((state) => state.toggleCart);
  const switchToGuestCart = useCartStore((state) => state.switchToGuestCart);
  const totalItems = useCartStore(selectTotalItems);
  const [showChangePasswordModal, setShowChangePasswordModal] = useState(false);
  const onSearch = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const trimmedQuery = searchQuery.trim();
    if (!trimmedQuery) return;

    navigate(`/search-results?search=${encodeURIComponent(trimmedQuery)}`);
    setSearchQuery("");
    setIsNavOpen(false);
  };

  const openAuthModal = (mode: AuthMode = "login") => {
    setAuthMode(mode);
    setIsAuthModalOpen(true);
  };

  const onLogin = () => {
    showToast("Successfully logged in!", "success");
  };

  const onLogout = () => {
    logout();
    switchToGuestCart();
    navigate("/");
    setIsUserMenuOpen(false);
    showToast("Successfully logged out", "info");
  };

  return (
    <>
      <nav className="navbar navbar-expand-lg main-navbar sticky-top">
        <div className="container">
          <Link
            className="navbar-brand d-flex align-items-center gap-2"
            to="/"
            onClick={() => setIsNavOpen(false)}
          >
            <div
              className="d-flex align-items-center justify-content-center rounded-2 bg-gold"
              style={{ width: "38px", height: "38px", flexShrink: 0 }}
            >
              <i className="bi bi-book" />
            </div>
            <span
              className="fw-bold fs-4"
              style={{
                color: "var(--brand-dark)",
                fontFamily: '"Lato", sans-serif',
              }}
            >
              Book<span className="text-gold">Worms</span>
            </span>
          </Link>

          <button
            className="navbar-toggler border-0 p-1"
            type="button"
            onClick={() => setIsNavOpen((current) => !current)}
            aria-label="Toggle navigation"
            aria-expanded={isNavOpen}
          >
            <i
              className="bi bi-list"
              style={{ fontSize: "1.6rem", color: "var(--brand-dark)" }}
            />
          </button>

          <div
            className={`collapse navbar-collapse${isNavOpen ? " show" : ""}`}
            id="mainNav"
          >
            <ul className="navbar-nav mx-auto gap-lg-1 py-3 py-lg-0">
              {navItems.map((item) => (
                <li className="nav-item" key={item.label}>
                  <NavLink
                    className="nav-link"
                    to={item.path}
                    onClick={() => setIsNavOpen(false)}
                  >
                    {item.label}
                  </NavLink>
                </li>
              ))}
            </ul>

            <div className="d-flex align-items-center gap-1 mt-2 mt-lg-0">
              <form
                className="d-flex me-2 position-relative"
                onSubmit={onSearch}
              >
                <input
                  type="text"
                  className="form-control form-control-sm rounded-pill px-3 py-1"
                  placeholder="Search books..."
                  value={searchQuery}
                  onChange={(event) => setSearchQuery(event.target.value)}
                  style={{
                    borderColor: "#c78b51",
                    minWidth: "160px",
                    fontSize: "0.85rem",
                  }}
                />
                <button
                  type="submit"
                  className="btn btn-sm position-absolute end-0 top-50 translate-middle-y"
                  style={{
                    color: "#c78b51",
                    border: "none",
                    background: "transparent",
                  }}
                >
                  <i className="bi bi-search" />
                </button>
              </form>

              <button
                className="icon-btn"
                onClick={toggleCart}
                aria-label="Cart"
              >
                <i className="bi bi-bag" />
                {totalItems > 0 && (
                  <span className="cart-pill">{totalItems}</span>
                )}
              </button>

              {!isLoggedIn ? (
                <button
                  type="button"
                  className="icon-btn"
                  aria-label="Account"
                  onClick={() => openAuthModal("login")}
                >
                  <i className="bi bi-person" />
                </button>
              ) : (
                <div className="dropdown d-inline-block">
                  <button
                    className="icon-btn dropdown-toggle"
                    type="button"
                    onClick={() => setIsUserMenuOpen((current) => !current)}
                    aria-expanded={isUserMenuOpen}
                    style={{ border: "none", background: "transparent" }}
                  >
                    <i className="bi bi-person-check fs-5" />
                  </button>

                  <ul
                    className={`dropdown-menu dropdown-menu-end mt-2 shadow border-0${
                      isUserMenuOpen ? " show" : ""
                    }`}
                    style={{ minWidth: "200px" }}
                  >
                    <li>
                      <Link
                        className="dropdown-item py-2"
                        to={
                          userRole === "Admin"
                            ? "/admin-dashboard"
                            : "/my-account"
                        }
                        onClick={() => setIsUserMenuOpen(false)}
                      >
                        <i
                          className={`bi ${
                            userRole === "Admin"
                              ? "bi-speedometer2"
                              : "bi-house-door"
                          } me-2 text-gold`}
                        />
                        {userRole === "Admin"
                          ? "Admin Dashboard"
                          : "My Account"}
                      </Link>
                    </li>
                    <li>
                      <Link
                        className="dropdown-item py-2"
                        to="/profile"
                        onClick={() => setIsUserMenuOpen(false)}
                      >
                        <i className="bi bi-person-circle me-2 text-gold" />
                        Profile
                      </Link>
                    </li>
                    <li>
                      <hr className="dropdown-divider" />
                    </li>
                    <li>
                      <button
                        className="dropdown-item py-2"
                        onClick={() => {
                          setShowChangePasswordModal(true);
                          setIsUserMenuOpen(false);
                        }}
                      >
                        <i className="bi bi-shield-lock me-2 text-gold" />
                        Change Password
                      </button>
                    </li>
                    <li>
                      <button
                        className="dropdown-item py-2 text-danger"
                        onClick={onLogout}
                      >
                        <i className="bi bi-box-arrow-right me-2" />
                        Logout
                      </button>
                    </li>
                  </ul>
                </div>
              )}

              <Link
                to="/cart"
                className="btn btn-gold btn-sm ms-2 px-3 text-uppercase fw-bold"
                style={{ letterSpacing: "0.05em", fontSize: "0.75rem" }}
              >
                <i className="bi bi-bag-check me-1" />
                Cart
              </Link>
            </div>
          </div>
        </div>
      </nav>

      <AuthModal
        isOpen={isAuthModalOpen}
        initialMode={authMode}
        onClose={() => setIsAuthModalOpen(false)}
        onLoggedIn={onLogin}
      />

      {showChangePasswordModal && (
        <ChangePasswordModal
          onClose={() => setShowChangePasswordModal(false)}
        />
      )}
    </>
  );
}
