// frontEnd/src/app/components/customer/customer-password-panel/customer-password-panel.component.ts
import { Component } from "@angular/core";
import { CommonModule } from "@angular/common";
import { ChangePasswordModalComponent } from "../../change-password-modal/change-password-modal.component";

@Component({
  selector: "app-customer-password-panel",
  standalone: true,
  imports: [CommonModule, ChangePasswordModalComponent],
  templateUrl: "./customer-password-panel.component.html",
})
export class CustomerPasswordPanelComponent {
  showModal = false;
}

<div class="section-heading">Change Password</div>

<div class="card-box">
  <div class="d-flex align-items-center gap-3 mb-3">
    <div
      style="
        width: 48px;
        height: 48px;
        border-radius: 12px;
        background: var(--brand-warm);
        display: flex;
        align-items: center;
        justify-content: center;
      "
    >
      <i
        class="bi bi-shield-lock"
        style="font-size: 1.3rem; color: var(--gold)"
      ></i>
    </div>
    <div>
      <div style="font-weight: 700; font-size: 0.95rem">
        Password & Security
      </div>
      <div style="font-size: 0.82rem; color: var(--brand-gray)">
        Manage your account password
      </div>
    </div>
  </div>
  <p style="font-size: 0.85rem; color: var(--brand-gray); margin-bottom: 20px">
    Keep your account secure by using a strong, unique password that you don't
    use on other sites.
  </p>
  <div
    style="
      margin-bottom: 16px;
      padding: 14px 16px;
      background: var(--brand-bg);
      border-radius: 10px;
      border: 1px solid var(--brand-border);
    "
  >
    <div style="font-weight: 600; font-size: 0.85rem; margin-bottom: 8px">
      Password Requirements:
    </div>
    <ul
      style="
        font-size: 0.82rem;
        color: var(--brand-gray);
        margin: 0;
        padding-left: 18px;
        line-height: 1.8;
      "
    >
      <li>At least 8 characters long</li>
      <li>Contains at least one uppercase letter</li>
      <li>Contains at least one number</li>
      <li>Contains at least one special character</li>
    </ul>
  </div>
  <button class="btn-gold-cust" (click)="showModal = true">
    <i class="bi bi-pencil-square me-1"></i> Change Password
  </button>
</div>

@if (showModal) {
  <app-change-password-modal
    (close)="showModal = false"
  ></app-change-password-modal>
}

// react-frontend/src/components/customer/customer-password-panel/CustomerPasswordPanel.tsx
import { useState } from "react";
import ChangePasswordModal from "../../change-password-modal/ChangePasswordModal";

export default function CustomerPasswordPanel() {
  const [showModal, setShowModal] = useState(false);

  return (
    <>
      <div className="section-heading">Change Password</div>

      <div className="card-box">
        <div className="d-flex align-items-center gap-3 mb-3">
          <div
            style={{
              width: 48,
              height: 48,
              borderRadius: 12,
              background: "var(--brand-warm)",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
            }}
          >
            <i
              className="bi bi-shield-lock"
              style={{ fontSize: "1.3rem", color: "var(--gold)" }}
            />
          </div>
          <div>
            <div style={{ fontWeight: 700, fontSize: "0.95rem" }}>
              Password & Security
            </div>
            <div style={{ fontSize: "0.82rem", color: "var(--brand-gray)" }}>
              Manage your account password
            </div>
          </div>
        </div>

        <p
          style={{
            fontSize: "0.85rem",
            color: "var(--brand-gray)",
            marginBottom: 20,
          }}
        >
          Keep your account secure by using a strong, unique password that you
          don't use on other sites.
        </p>

        <div
          style={{
            marginBottom: 16,
            padding: "14px 16px",
            background: "var(--brand-bg)",
            borderRadius: 10,
            border: "1px solid var(--brand-border)",
          }}
        >
          <div
            style={{ fontWeight: 600, fontSize: "0.85rem", marginBottom: 8 }}
          >
            Password Requirements:
          </div>
          <ul
            style={{
              fontSize: "0.82rem",
              color: "var(--brand-gray)",
              margin: 0,
              paddingLeft: 18,
              lineHeight: 1.8,
            }}
          >
            <li>At least 8 characters long</li>
            <li>Contains at least one uppercase letter</li>
            <li>Contains at least one number</li>
            <li>Contains at least one special character</li>
          </ul>
        </div>

        <button className="btn-gold-cust" onClick={() => setShowModal(true)}>
          <i className="bi bi-pencil-square me-1" /> Change Password
        </button>
      </div>

      {showModal && <ChangePasswordModal onClose={() => setShowModal(false)} />}
    </>
  );
}
