// frontEnd/src/app/components/customer/customer-profile-panel/customer-profile-panel.component.ts
import { Component, EventEmitter, OnInit, Output, inject } from "@angular/core";
import { CommonModule } from "@angular/common";
import {
  FormBuilder,
  FormGroup,
  ReactiveFormsModule,
  Validators,
} from "@angular/forms";
import { IUserDetails } from "../../../models/Auth/UserDetails/iuser-details";
import { IUpdateUserRequest } from "../../../models/Auth/UserDetails/iupdate-user-request";
import { ApiUserService } from "../../../services/users/api-user.service";
import { ToastService } from "../../../services/toast.service";
import { getImageUrl } from "../../../Utils/cloudinary.utils";

@Component({
  selector: "app-customer-profile-panel",
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule],
  templateUrl: "./customer-profile-panel.component.html",
})
export class CustomerProfilePanelComponent implements OnInit {
  @Output() profileUpdated = new EventEmitter<IUserDetails>();

  private fb = inject(FormBuilder);
  private userService = inject(ApiUserService);
  private toastService = inject(ToastService);

  profileForm: FormGroup;
  currentUserData: IUserDetails | null = null;
  currentImageUrl: string | null = null;
  selectedImage: File | null = null;
  isLoading = true;
  isSubmitting = false;

  protected getImageUrl = getImageUrl;

  constructor() {
    this.profileForm = this.fb.group({
      displayName: ["", [Validators.maxLength(100)]],
      firstName: ["", [Validators.minLength(2), Validators.maxLength(50)]],
      lastName: ["", [Validators.minLength(2), Validators.maxLength(50)]],
      email: [{ value: "", disabled: true }],
      phoneNumber: ["", [Validators.pattern(/^\+?[0-9\s-]{7,15}$/)]],
    });
  }

  ngOnInit(): void {
    this.loadProfile();
  }

  loadProfile(): void {
    this.isLoading = true;

    this.userService.getUserDetails().subscribe({
      next: (user) => {
        this.currentUserData = user;
        this.currentImageUrl = user.imagePath ?? null;
        this.patchForm(user);
        this.isLoading = false;
      },
      error: () => {
        this.isLoading = false;
        this.toastService.show("Failed to load profile information", "error");
      },
    });
  }

  resetForm(): void {
    if (!this.currentUserData) return;

    this.patchForm(this.currentUserData);
    this.currentImageUrl = this.currentUserData.imagePath ?? null;
    this.selectedImage = null;
  }

  onSubmit(): void {
    if (this.profileForm.invalid) {
      this.profileForm.markAllAsTouched();
      return;
    }

    this.isSubmitting = true;
    const values = this.profileForm.getRawValue();
    const updateRequest: IUpdateUserRequest = {
      displayName: values.displayName?.trim() || undefined,
      firstName: values.firstName?.trim() || undefined,
      lastName: values.lastName?.trim() || undefined,
      phoneNumber: values.phoneNumber?.trim() || undefined,
      image: this.selectedImage ?? undefined,
    };

    this.userService.updateUser(updateRequest).subscribe({
      next: () => {
        const displayName = values.displayName?.trim();
        const firstName = values.firstName?.trim();
        const lastName = values.lastName?.trim();
        const phoneNumber = values.phoneNumber?.trim();
        const updatedUser: IUserDetails = {
          ...(this.currentUserData ?? { email: values.email }),
          displayName: displayName || this.currentUserData?.displayName,
          firstName: firstName || this.currentUserData?.firstName,
          lastName: lastName || this.currentUserData?.lastName,
          phoneNumber: phoneNumber || this.currentUserData?.phoneNumber,
          imagePath: this.currentImageUrl ?? undefined,
        };

        this.currentUserData = updatedUser;
        this.selectedImage = null;
        this.isSubmitting = false;
        this.profileUpdated.emit(updatedUser);
        this.toastService.show("Profile updated successfully", "success");
      },
      error: (err) => {
        this.isSubmitting = false;
        const message =
          err?.error?.detail ||
          err?.error?.title ||
          "Failed to update profile information";
        this.toastService.show(message, "error");
      },
    });
  }

  onImageSelected(event: Event): void {
    const input = event.target as HTMLInputElement;
    const file = input.files?.[0];
    if (!file) return;

    this.selectedImage = file;
    const reader = new FileReader();
    reader.onload = (e) => {
      this.currentImageUrl = e.target?.result as string;
    };
    reader.readAsDataURL(file);
  }

  onImageError(): void {
    this.currentImageUrl = null;
  }

  private patchForm(user: IUserDetails): void {
    this.profileForm.patchValue({
      displayName: user.displayName ?? "",
      firstName: user.firstName ?? "",
      lastName: user.lastName ?? "",
      email: user.email ?? "",
      phoneNumber: user.phoneNumber ?? "",
    });
    this.profileForm.markAsPristine();
  }
}

<div class="section-heading">Profile Info</div>

@if (isLoading) {
  <div class="card-box text-center py-4">
    <div class="spinner-border text-gold" role="status"></div>
    <div class="text-muted mt-3">Loading profile information...</div>
  </div>
} @else {
  <form [formGroup]="profileForm" (ngSubmit)="onSubmit()">
    <div class="card-box">
      <div class="d-flex align-items-center gap-3 mb-4">
        <div
          class="customer-avatar-lg"
          style="width: 64px; height: 64px; font-size: 1.15rem"
        >
          @if (currentImageUrl) {
            <img
              [src]="getImageUrl(currentImageUrl, 'avatar')"
              alt="Profile image"
              style="
                width: 100%;
                height: 100%;
                border-radius: 50%;
                object-fit: cover;
              "
              (error)="onImageError()"
            />
          } @else {
            <i class="bi bi-person-fill"></i>
          }
        </div>
        <div style="flex: 1">
          <div class="form-label-sm">Profile Image</div>
          <input
            class="form-control-custom"
            type="file"
            accept="image/jpeg,image/png,image/webp"
            (change)="onImageSelected($event)"
          />
          <div
            style="
              font-size: 0.75rem;
              color: var(--brand-gray);
              margin-top: 5px;
            "
          >
            @if (selectedImage) {
              Selected: {{ selectedImage.name }}
            } @else {
              JPG, PNG, or WebP up to 10MB.
            }
          </div>
        </div>
      </div>

      <div class="row g-3">
        <div class="col-md-6">
          <div class="form-label-sm">Display Name</div>
          <input
            class="form-control-custom"
            type="text"
            formControlName="displayName"
            placeholder="How your name appears"
          />
        </div>
        <div class="col-md-6">
          <div class="form-label-sm">Email Address</div>
          <input
            class="form-control-custom"
            type="email"
            formControlName="email"
          />
        </div>
        <div class="col-md-6">
          <div class="form-label-sm">First Name</div>
          <input
            class="form-control-custom"
            type="text"
            formControlName="firstName"
            placeholder="First name"
          />
          @if (
            profileForm.get("firstName")?.touched &&
            profileForm.get("firstName")?.invalid
          ) {
            <div style="font-size: 0.75rem; color: #dc3545; margin-top: 5px">
              First name must be 2-50 characters.
            </div>
          }
        </div>
        <div class="col-md-6">
          <div class="form-label-sm">Last Name</div>
          <input
            class="form-control-custom"
            type="text"
            formControlName="lastName"
            placeholder="Last name"
          />
          @if (
            profileForm.get("lastName")?.touched &&
            profileForm.get("lastName")?.invalid
          ) {
            <div style="font-size: 0.75rem; color: #dc3545; margin-top: 5px">
              Last name must be 2-50 characters.
            </div>
          }
        </div>
        <div class="col-md-6">
          <div class="form-label-sm">Phone Number</div>
          <input
            class="form-control-custom"
            type="tel"
            formControlName="phoneNumber"
            placeholder="+20 1234567890"
          />
          @if (
            profileForm.get("phoneNumber")?.touched &&
            profileForm.get("phoneNumber")?.invalid
          ) {
            <div style="font-size: 0.75rem; color: #dc3545; margin-top: 5px">
              Enter a valid phone number.
            </div>
          }
        </div>
      </div>
      <div class="d-flex gap-2 mt-4">
        <button
          class="btn-gold-cust d-flex align-items-center gap-2"
          type="submit"
          [disabled]="profileForm.invalid || isSubmitting"
        >
          @if (isSubmitting) {
            <span
              class="spinner-border spinner-border-sm"
              role="status"
              aria-hidden="true"
            ></span>
          } @else {
            <i class="bi bi-check2"></i>
          }
          Save Changes
        </button>
        <button
          class="btn-outline-cust"
          type="button"
          [disabled]="isSubmitting"
          (click)="resetForm()"
        >
          Cancel
        </button>
      </div>
    </div>
  </form>
}

// react-frontend/src/components/customer/customer-profile-panel/CustomerProfilePanel.tsx
import { useState, useEffect, useCallback } from "react";
import * as authService from "../../../services/auth/authService";
import { getImageUrl } from "../../../utils/imageUtils";
import { showToast } from "../../../utils/toast";
import type { IUserDetails } from "../../../types/auth.types";

const PHONE_REGEX = /^\+?[0-9\s-]{7,15}$/;

interface CustomerProfilePanelProps {
  onProfileUpdated?: (user: IUserDetails) => void;
}

interface FormState {
  displayName: string;
  firstName: string;
  lastName: string;
  email: string;
  phoneNumber: string;
}

const emptyForm = (): FormState => ({
  displayName: "",
  firstName: "",
  lastName: "",
  email: "",
  phoneNumber: "",
});

export default function CustomerProfilePanel({
  onProfileUpdated,
}: CustomerProfilePanelProps) {
  const [form, setForm] = useState<FormState>(emptyForm());
  const [touched, setTouched] = useState<
    Partial<Record<keyof FormState, boolean>>
  >({});
  const [currentUserData, setCurrentUserData] = useState<IUserDetails | null>(
    null,
  );
  const [currentImageUrl, setCurrentImageUrl] = useState<string | null>(null);
  const [selectedImage, setSelectedImage] = useState<File | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isSubmitting, setIsSubmitting] = useState(false);

  // ── validation ────────────────────────────────────────────────────────────
  const errors = {
    firstName:
      form.firstName.length > 0 &&
      (form.firstName.length < 2 || form.firstName.length > 50),
    lastName:
      form.lastName.length > 0 &&
      (form.lastName.length < 2 || form.lastName.length > 50),
    phoneNumber:
      form.phoneNumber.length > 0 && !PHONE_REGEX.test(form.phoneNumber),
  };
  const isFormInvalid = Object.values(errors).some(Boolean);

  // ── load profile ──────────────────────────────────────────────────────────
  const patchForm = useCallback((user: IUserDetails) => {
    setForm({
      displayName: user.displayName ?? "",
      firstName: user.firstName ?? "",
      lastName: user.lastName ?? "",
      email: user.email ?? "",
      phoneNumber: user.phoneNumber ?? "",
    });
    setTouched({});
  }, []);

  const loadProfile = useCallback(() => {
    setIsLoading(true);
    authService
      .getUserDetails()
      .then((res) => {
        const user = res.data;
        setCurrentUserData(user);
        setCurrentImageUrl(user.imagePath ?? null);
        patchForm(user);
      })
      .catch(() => showToast("Failed to load profile information", "error"))
      .finally(() => setIsLoading(false));
  }, [patchForm]);

  useEffect(() => {
    loadProfile();
  }, [loadProfile]);

  // ── handlers ──────────────────────────────────────────────────────────────
  const onChange = (field: keyof FormState, value: string) =>
    setForm((prev) => ({ ...prev, [field]: value }));

  const onBlur = (field: keyof FormState) =>
    setTouched((prev) => ({ ...prev, [field]: true }));

  const resetForm = () => {
    if (!currentUserData) return;
    patchForm(currentUserData);
    setCurrentImageUrl(currentUserData.imagePath ?? null);
    setSelectedImage(null);
  };

  const onImageSelected = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    setSelectedImage(file);
    const reader = new FileReader();
    reader.onload = (ev) => setCurrentImageUrl(ev.target?.result as string);
    reader.readAsDataURL(file);
  };

  const onImageError = () => setCurrentImageUrl(null);

  const onSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    // mark all as touched
    setTouched({ firstName: true, lastName: true, phoneNumber: true });
    if (isFormInvalid) return;

    setIsSubmitting(true);
    try {
      await authService.updateUser({
        displayName: form.displayName.trim() || undefined,
        firstName: form.firstName.trim() || undefined,
        lastName: form.lastName.trim() || undefined,
        phoneNumber: form.phoneNumber.trim() || undefined,
        image: selectedImage ?? undefined,
      });

      const updatedUser: IUserDetails = {
        ...(currentUserData ?? { email: form.email }),
        displayName: form.displayName.trim() || currentUserData?.displayName,
        firstName: form.firstName.trim() || currentUserData?.firstName,
        lastName: form.lastName.trim() || currentUserData?.lastName,
        phoneNumber: form.phoneNumber.trim() || currentUserData?.phoneNumber,
        imagePath: currentImageUrl ?? undefined,
      };

      setCurrentUserData(updatedUser);
      setSelectedImage(null);
      onProfileUpdated?.(updatedUser);
      showToast("Profile updated successfully", "success");
    } catch (err: any) {
      const message =
        err?.response?.data?.detail ||
        err?.response?.data?.title ||
        "Failed to update profile information";
      showToast(message, "error");
    } finally {
      setIsSubmitting(false);
    }
  };

  // ── render ────────────────────────────────────────────────────────────────
  return (
    <>
      <div className="section-heading">Profile Info</div>

      {isLoading ? (
        <div className="card-box text-center py-4">
          <div className="spinner-border text-gold" role="status" />
          <div className="text-muted mt-3">Loading profile information...</div>
        </div>
      ) : (
        <form onSubmit={onSubmit} noValidate>
          <div className="card-box">
            {/* Avatar + image upload */}
            <div className="d-flex align-items-center gap-3 mb-4">
              <div
                className="customer-avatar-lg"
                style={{ width: 64, height: 64, fontSize: "1.15rem" }}
              >
                {currentImageUrl ? (
                  <img
                    src={getImageUrl(currentImageUrl, "avatar")}
                    alt="Profile image"
                    style={{
                      width: "100%",
                      height: "100%",
                      borderRadius: "50%",
                      objectFit: "cover",
                    }}
                    onError={onImageError}
                  />
                ) : (
                  <i className="bi bi-person-fill" />
                )}
              </div>
              <div style={{ flex: 1 }}>
                <div className="form-label-sm">Profile Image</div>
                <input
                  className="form-control-custom"
                  type="file"
                  accept="image/jpeg,image/png,image/webp"
                  onChange={onImageSelected}
                />
                <div
                  style={{
                    fontSize: "0.75rem",
                    color: "var(--brand-gray)",
                    marginTop: 5,
                  }}
                >
                  {selectedImage
                    ? `Selected: ${selectedImage.name}`
                    : "JPG, PNG, or WebP up to 10MB."}
                </div>
              </div>
            </div>

            {/* Form fields */}
            <div className="row g-3">
              <div className="col-md-6">
                <div className="form-label-sm">Display Name</div>
                <input
                  className="form-control-custom"
                  type="text"
                  value={form.displayName}
                  onChange={(e) => onChange("displayName", e.target.value)}
                  placeholder="How your name appears"
                />
              </div>
              <div className="col-md-6">
                <div className="form-label-sm">Email Address</div>
                <input
                  className="form-control-custom"
                  type="email"
                  value={form.email}
                  disabled
                  readOnly
                />
              </div>
              <div className="col-md-6">
                <div className="form-label-sm">First Name</div>
                <input
                  className="form-control-custom"
                  type="text"
                  value={form.firstName}
                  onChange={(e) => onChange("firstName", e.target.value)}
                  onBlur={() => onBlur("firstName")}
                  placeholder="First name"
                />
                {touched.firstName && errors.firstName && (
                  <div
                    style={{
                      fontSize: "0.75rem",
                      color: "#dc3545",
                      marginTop: 5,
                    }}
                  >
                    First name must be 2-50 characters.
                  </div>
                )}
              </div>
              <div className="col-md-6">
                <div className="form-label-sm">Last Name</div>
                <input
                  className="form-control-custom"
                  type="text"
                  value={form.lastName}
                  onChange={(e) => onChange("lastName", e.target.value)}
                  onBlur={() => onBlur("lastName")}
                  placeholder="Last name"
                />
                {touched.lastName && errors.lastName && (
                  <div
                    style={{
                      fontSize: "0.75rem",
                      color: "#dc3545",
                      marginTop: 5,
                    }}
                  >
                    Last name must be 2-50 characters.
                  </div>
                )}
              </div>
              <div className="col-md-6">
                <div className="form-label-sm">Phone Number</div>
                <input
                  className="form-control-custom"
                  type="tel"
                  value={form.phoneNumber}
                  onChange={(e) => onChange("phoneNumber", e.target.value)}
                  onBlur={() => onBlur("phoneNumber")}
                  placeholder="+20 1234567890"
                />
                {touched.phoneNumber && errors.phoneNumber && (
                  <div
                    style={{
                      fontSize: "0.75rem",
                      color: "#dc3545",
                      marginTop: 5,
                    }}
                  >
                    Enter a valid phone number.
                  </div>
                )}
              </div>
            </div>

            {/* Actions */}
            <div className="d-flex gap-2 mt-4">
              <button
                className="btn-gold-cust d-flex align-items-center gap-2"
                type="submit"
                disabled={isFormInvalid || isSubmitting}
              >
                {isSubmitting ? (
                  <span
                    className="spinner-border spinner-border-sm"
                    role="status"
                    aria-hidden="true"
                  />
                ) : (
                  <i className="bi bi-check2" />
                )}
                Save Changes
              </button>
              <button
                className="btn-outline-cust"
                type="button"
                disabled={isSubmitting}
                onClick={resetForm}
              >
                Cancel
              </button>
            </div>
          </div>
        </form>
      )}
    </>
  );
}
