// frontEnd/src/app/components/auth-modal/auth-modal.component.ts
import {
  AfterViewInit,
  ChangeDetectorRef,
  Component,
  ElementRef,
  EventEmitter,
  NgZone,
  OnDestroy,
  Output,
  ViewChild,
} from "@angular/core";
import { CommonModule } from "@angular/common";
import {
  ReactiveFormsModule,
  FormBuilder,
  FormGroup,
  Validators,
} from "@angular/forms";
import { ApiUserService } from "../../services/users/api-user.service";
import { ToastService } from "../../services/toast.service";
import { CartService } from "../../services/cart.service";

type AuthMode = "login" | "signup";

@Component({
  selector: "app-auth-modal",
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule],
  templateUrl: "./auth-modal.component.html",
  styleUrl: "./auth-modal.component.css",
})
export class AuthModalComponent implements AfterViewInit, OnDestroy {
  @Output() loggedIn = new EventEmitter<any>();
  @ViewChild("authModal") modalRef?: ElementRef<HTMLDivElement>;

  authForm: FormGroup;
  private authMode: AuthMode = "login";
  private modalInstance?: { show: () => void; hide: () => void };
  private readonly handleHidden = () => {
    this.zone.run(() => {
      this.setAuthMode("login");
    });
  };

  get isLogin() {
    return this.authMode === "login";
  }

  constructor(
    private fb: FormBuilder,
    public userService: ApiUserService,
    private toastService: ToastService,
    private zone: NgZone,
    private cdr: ChangeDetectorRef,
    private cartService: CartService,
  ) {
    this.authForm = fb.group(
      {
        username: [""],
        email: ["", [Validators.required, Validators.email]],
        password: ["", [Validators.required, Validators.minLength(6)]],
        confirmPassword: [""],
      },
      { validators: this.passwordMatchValidator },
    );
  }

  ngAfterViewInit() {
    const modalElement = this.modalRef?.nativeElement;
    const bootstrapModal = (window as any).bootstrap?.Modal;

    if (!modalElement || !bootstrapModal) return;

    this.modalInstance = bootstrapModal.getOrCreateInstance(modalElement);
    modalElement.addEventListener("hidden.bs.modal", this.handleHidden);
  }

  ngOnDestroy() {
    this.modalRef?.nativeElement.removeEventListener(
      "hidden.bs.modal",
      this.handleHidden,
    );
  }

  open(mode: AuthMode = "login") {
    this.setAuthMode(mode);
    this.modalInstance?.show();
  }

  setLoginMode(event?: Event) {
    event?.preventDefault();
    event?.stopPropagation();
    this.setAuthMode("login");
  }

  setSignupMode(event?: Event) {
    event?.preventDefault();
    event?.stopPropagation();
    this.setAuthMode("signup");
  }

  passwordMatchValidator(g: FormGroup) {
    const password = g.get("password")?.value;
    const confirm = g.get("confirmPassword")?.value;

    if (!confirm) return null;

    return password === confirm ? null : { passwordMismatch: true };
  }

  onSubmit() {
    if (this.authForm.invalid) return;

    const { email, password, username } = this.authForm.value;
    if (this.isLogin) {
      this.userService.login(email, password).subscribe({
        next: (res) => {
          this.userService.saveToken(res.token);
          this.cartService.syncGuestCartAfterLogin();
          console.log(res.token);
          this.closeModal();
          this.loggedIn.emit();
        },
        error: () => {
          this.toastService.show("Invalid email or password", "error");
        },
      });

      return;
    }

    if (!username) {
      this.toastService.show("Username is required", "error");
      return;
    }
    this.userService.registerUser(email, password, username).subscribe({
      next: (res) => {
        this.userService.saveToken(res.token);
        this.cartService.syncGuestCartAfterLogin();
        this.closeModal();
        this.loggedIn.emit();
      },
      error: () => {
        this.toastService.show("Registration failed. Try again.", "error");
      },
    });
  }

  private closeModal() {
    this.modalInstance?.hide();
    this.setAuthMode("login");
  }

  private setAuthMode(mode: AuthMode) {
    this.authMode = mode;
    this.authForm.reset({
      username: "",
      email: "",
      password: "",
      confirmPassword: "",
    });
    this.authForm.markAsPristine();
    this.authForm.markAsUntouched();
    const confirmPasswordControl = this.authForm.get("confirmPassword");
    if (!confirmPasswordControl) return;

    const displayNameControl = this.authForm.get("username");
    if (!displayNameControl) return;
    if (this.isLogin) {
      confirmPasswordControl.clearValidators();
      displayNameControl?.clearValidators();
    } else {
      confirmPasswordControl.setValidators([Validators.required]);
      displayNameControl?.setValidators([
        Validators.required,
        Validators.minLength(3),
        Validators.maxLength(50),
      ]);
    }

    confirmPasswordControl.updateValueAndValidity({ emitEvent: false });
    displayNameControl?.updateValueAndValidity({ emitEvent: false });
    this.authForm.updateValueAndValidity({ emitEvent: false });
    this.cdr.detectChanges();
  }
}

<div
  #authModal
  class="modal fade"
  id="authModal"
  tabindex="-1"
  aria-labelledby="authModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog modal-dialog-centered">
    <div
      class="modal-content border-0 shadow"
      style="border-radius: 12px; overflow: hidden"
    >
      <div class="modal-header border-0 pb-0 justify-content-end p-3">
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="modal-body p-4 pt-1">
        <div class="text-center mb-4">
          <h4 class="fw-bold" style="font-family: &quot;Lato&quot;, sans-serif">
            {{ isLogin ? "Welcome Back" : "Create Account" }}
          </h4>
          <p class="text-muted small">
            {{
              isLogin
                ? "Login to access your cart and orders."
                : "Sign up to get started."
            }}
          </p>
        </div>

        <form [formGroup]="authForm" (ngSubmit)="onSubmit()" autocomplete="off">
          <div class="mb-3">
            <label class="form-label small fw-semibold text-muted"
              >Email Address</label
            >
            <input
              type="email"
              class="form-control"
              formControlName="email"
              placeholder="name@example.com"
            />
          </div>
          <div class="mb-3" *ngIf="!isLogin">
            <label class="form-label small fw-semibold text-muted"
              >Userame</label
            >
            <input
              type="text"
              class="form-control"
              formControlName="username"
              placeholder="AXZY"
            />
          </div>

          <div class="mb-4">
            <label class="form-label small fw-semibold text-muted"
              >Password</label
            >
            <input
              type="password"
              class="form-control"
              formControlName="password"
              placeholder="********"
            />
          </div>
          <div class="mb-4" *ngIf="!isLogin">
            <label class="form-label small fw-semibold text-muted"
              >Confirm Password</label
            >
            <input
              type="password"
              class="form-control"
              formControlName="confirmPassword"
              placeholder="********"
              autocomplete="new-password"
            />
            <div
              class="text-danger small mt-1"
              *ngIf="
                authForm.errors?.['passwordMismatch'] &&
                (authForm.get('confirmPassword')?.touched ||
                  authForm.get('confirmPassword')?.dirty)
              "
            >
              Passwords do not match.
            </div>
          </div>

          <button
            type="submit"
            class="btn btn-gold w-100 fw-bold py-2 mb-3"
            [disabled]="authForm.invalid"
          >
            {{ isLogin ? "Sign In" : "Sign Up" }}
          </button>
        </form>

        <div class="text-center">
          <p class="small text-muted mb-0">
            {{
              isLogin ? "Don't have an account?" : "Already have an account?"
            }}
            @if (isLogin) {
              <button
                type="button"
                class="btn btn-link p-0 text-decoration-none fw-semibold text-gold"
                (click)="setSignupMode($event)"
              >
                Sign up
              </button>
            } @else {
              <button
                type="button"
                class="btn btn-link p-0 text-decoration-none fw-semibold text-gold"
                (click)="setLoginMode($event)"
              >
                Log in
              </button>
            }
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

// react-frontend/src/components/auth-modal/AuthModal.tsx
import { useEffect, useState, type FormEvent } from "react";
import { login, registerUser } from "../../services/auth/authService";
import { useAuthStore } from "../../services/auth/useAuthStore";
import { useCartStore } from "../../store/useCartStore";
import { showToast } from "../../utils/toast";

type AuthMode = "login" | "signup";

interface AuthModalProps {
  isOpen: boolean;
  initialMode: AuthMode;
  onClose: () => void;
  onLoggedIn: () => void;
}

const initialForm = {
  username: "",
  email: "",
  password: "",
  confirmPassword: "",
};

export default function AuthModal({
  isOpen,
  initialMode,
  onClose,
  onLoggedIn,
}: AuthModalProps) {
  const [mode, setMode] = useState<AuthMode>(initialMode);
  const [form, setForm] = useState(initialForm);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const saveToken = useAuthStore((state) => state.saveToken);
  const syncGuestCartAfterLogin = useCartStore(
    (state) => state.syncGuestCartAfterLogin,
  );

  const isLogin = mode === "login";
  const passwordsMismatch =
    !isLogin &&
    form.confirmPassword.length > 0 &&
    form.password !== form.confirmPassword;
  const isFormInvalid =
    !form.email.trim() ||
    form.password.length < 6 ||
    (!isLogin &&
      (!form.username.trim() ||
        form.username.trim().length < 3 ||
        passwordsMismatch));

  useEffect(() => {
    if (isOpen) {
      setMode(initialMode);
      setForm(initialForm);
    }
  }, [initialMode, isOpen]);

  const setAuthMode = (nextMode: AuthMode) => {
    setMode(nextMode);
    setForm(initialForm);
  };

  const closeModal = () => {
    setAuthMode("login");
    onClose();
  };

  const onSubmit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (isFormInvalid || isSubmitting) return;

    setIsSubmitting(true);
    try {
      const response = isLogin
        ? await login(form.email, form.password)
        : await registerUser(form.email, form.password, form.username);

      saveToken(response.data.token);
      await syncGuestCartAfterLogin();
      closeModal();
      onLoggedIn();
    } catch {
      showToast(
        isLogin ? "Invalid email or password" : "Registration failed. Try again.",
        "error",
      );
    } finally {
      setIsSubmitting(false);
    }
  };

  if (!isOpen) return null;

  return (
    <>
      <div className="modal-backdrop fade show" onClick={closeModal} />
      <div
        className="modal fade show d-block"
        id="authModal"
        tabIndex={-1}
        aria-labelledby="authModalLabel"
        aria-modal="true"
        role="dialog"
      >
        <div className="modal-dialog modal-dialog-centered">
          <div
            className="modal-content border-0 shadow"
            style={{ borderRadius: "12px", overflow: "hidden" }}
          >
            <div className="modal-header border-0 pb-0 justify-content-end p-3">
              <button
                type="button"
                className="btn-close"
                onClick={closeModal}
                aria-label="Close"
              />
            </div>
            <div className="modal-body p-4 pt-1">
              <div className="text-center mb-4">
                <h4
                  id="authModalLabel"
                  className="fw-bold"
                  style={{ fontFamily: '"Lato", sans-serif' }}
                >
                  {isLogin ? "Welcome Back" : "Create Account"}
                </h4>
                <p className="text-muted small">
                  {isLogin
                    ? "Login to access your cart and orders."
                    : "Sign up to get started."}
                </p>
              </div>

              <form onSubmit={onSubmit} autoComplete="off">
                <div className="mb-3">
                  <label className="form-label small fw-semibold text-muted">
                    Email Address
                  </label>
                  <input
                    type="email"
                    className="form-control"
                    value={form.email}
                    onChange={(event) =>
                      setForm((current) => ({
                        ...current,
                        email: event.target.value,
                      }))
                    }
                    placeholder="name@example.com"
                    required
                  />
                </div>

                {!isLogin && (
                  <div className="mb-3">
                    <label className="form-label small fw-semibold text-muted">
                      Username
                    </label>
                    <input
                      type="text"
                      className="form-control"
                      value={form.username}
                      onChange={(event) =>
                        setForm((current) => ({
                          ...current,
                          username: event.target.value,
                        }))
                      }
                      placeholder="AXZY"
                      required
                    />
                  </div>
                )}

                <div className="mb-4">
                  <label className="form-label small fw-semibold text-muted">
                    Password
                  </label>
                  <input
                    type="password"
                    className="form-control"
                    value={form.password}
                    onChange={(event) =>
                      setForm((current) => ({
                        ...current,
                        password: event.target.value,
                      }))
                    }
                    placeholder="********"
                    required
                  />
                </div>

                {!isLogin && (
                  <div className="mb-4">
                    <label className="form-label small fw-semibold text-muted">
                      Confirm Password
                    </label>
                    <input
                      type="password"
                      className="form-control"
                      value={form.confirmPassword}
                      onChange={(event) =>
                        setForm((current) => ({
                          ...current,
                          confirmPassword: event.target.value,
                        }))
                      }
                      placeholder="********"
                      autoComplete="new-password"
                      required
                    />
                    {passwordsMismatch && (
                      <div className="text-danger small mt-1">
                        Passwords do not match.
                      </div>
                    )}
                  </div>
                )}

                <button
                  type="submit"
                  className="btn btn-gold w-100 fw-bold py-2 mb-3"
                  disabled={isFormInvalid || isSubmitting}
                >
                  {isLogin ? "Sign In" : "Sign Up"}
                </button>
              </form>

              <div className="text-center">
                <p className="small text-muted mb-0">
                  {isLogin
                    ? "Don't have an account?"
                    : "Already have an account?"}{" "}
                  <button
                    type="button"
                    className="btn btn-link p-0 text-decoration-none fw-semibold text-gold"
                    onClick={() => setAuthMode(isLogin ? "signup" : "login")}
                  >
                    {isLogin ? "Sign up" : "Log in"}
                  </button>
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
