// react-frontend/src/components/customer/customer-sidebar/CustomerSidebar.tsx
type TabCounts = Partial<
  Record<"orders" | "reviews" | "addresses" | "notifications", number | null>
>;

interface CustomerSidebarProps {
  activePanel?: string;
  tabCounts?: TabCounts;
  onPanelChange?: (panel: string) => void;
  onSignOut?: () => void;
}

const navItems = [
  {
    section: "Account",
    links: [
      {
        id: "orders",
        icon: "bi-bag-check",
        label: "My Orders",
        badge: "orders" as const,
      },
      {
        id: "reviews",
        icon: "bi-chat-square-text",
        label: "My Reviews",
        badge: "reviews" as const,
      },
    ],
  },
  {
    section: "Settings",
    links: [
      { id: "profile", icon: "bi-person", label: "Profile Info", badge: null },
      {
        id: "addresses",
        icon: "bi-geo-alt",
        label: "Saved Addresses",
        badge: "addresses" as const,
      },
      {
        id: "notifications",
        icon: "bi-bell",
        label: "Notifications",
        badge: "notifications" as const,
      },
      { id: "password", icon: "bi-lock", label: "Password", badge: null },
    ],
  },
];

export default function CustomerSidebar({
  activePanel = "orders",
  tabCounts = {},
  onPanelChange,
  onSignOut,
}: CustomerSidebarProps) {
  return (
    <div className="account-sidebar">
      {navItems.map((group, groupIndex) => (
        <div key={group.section}>
          {groupIndex > 0 && <div className="side-divider" />}
          <div className="side-section-label">{group.section}</div>
          {group.links.map((link) => {
            const count = link.badge ? tabCounts[link.badge] : null;
            return (
              <a
                key={link.id}
                className={`side-nav-link${activePanel === link.id ? " active" : ""}`}
                onClick={() => onPanelChange?.(link.id)}
                style={{ cursor: "pointer" }}
              >
                <i className={`bi ${link.icon}`} /> {link.label}
                {count !== null && count !== undefined && (
                  <span className="side-badge">{count}</span>
                )}
              </a>
            );
          })}
        </div>
      ))}

      <div className="side-divider" />
      <a
        className="side-nav-link"
        style={{ color: "#dc3545", cursor: "pointer" }}
        onClick={onSignOut}
      >
        <i className="bi bi-box-arrow-right" /> Sign Out
      </a>
    </div>
  );
}

// frontEnd/src/app/components/customer/customer-sidebar/customer-sidebar.component.ts
import { Component, EventEmitter, Input, Output } from "@angular/core";
import { CommonModule } from "@angular/common";

type CustomerSidebarTabCounts = Partial<
  Record<"orders" | "reviews" | "addresses" | "notifications", number | null>
>;

@Component({
  selector: "app-customer-sidebar",
  standalone: true,
  imports: [CommonModule],
  templateUrl: "./customer-sidebar.component.html",
})
export class CustomerSidebarComponent {
  @Input() activePanel: string = "orders";
  @Input() tabCounts: CustomerSidebarTabCounts = {};
  @Output() panelChange = new EventEmitter<string>();
  @Output() signOut = new EventEmitter<void>();

  showPanel(panelId: string) {
    this.panelChange.emit(panelId);
  }

  onSignOut(): void {
    this.signOut.emit();
  }
}

<div class="account-sidebar">
  <div class="side-section-label">Account</div>
  <a
    class="side-nav-link"
    [class.active]="activePanel === 'orders'"
    (click)="showPanel('orders')"
  >
    <i class="bi bi-bag-check"></i> My Orders
    @if (tabCounts.orders !== null && tabCounts.orders !== undefined) {
      <span class="side-badge">{{ tabCounts.orders }}</span>
    }
  </a>
  <!--
    <a class="side-nav-link" [class.active]="activePanel === 'wishlist'" (click)="showPanel('wishlist')">
        <i class="bi bi-heart"></i> Wishlist
        <span class="side-badge">8</span>
    </a>
    -->
  <a
    class="side-nav-link"
    [class.active]="activePanel === 'reviews'"
    (click)="showPanel('reviews')"
  >
    <i class="bi bi-chat-square-text"></i> My Reviews
    @if (tabCounts.reviews !== null && tabCounts.reviews !== undefined) {
      <span class="side-badge">{{ tabCounts.reviews }}</span>
    }
  </a>
  <!--
    <a class="side-nav-link" [class.active]="activePanel === 'rewards'" (click)="showPanel('rewards')">
        <i class="bi bi-star"></i> Rewards & Loyalty
    </a>
    -->
  <div class="side-divider"></div>
  <div class="side-section-label">Settings</div>
  <a
    class="side-nav-link"
    [class.active]="activePanel === 'profile'"
    (click)="showPanel('profile')"
  >
    <i class="bi bi-person"></i> Profile Info
  </a>
  <a
    class="side-nav-link"
    [class.active]="activePanel === 'addresses'"
    (click)="showPanel('addresses')"
  >
    <i class="bi bi-geo-alt"></i> Saved Addresses
    @if (tabCounts.addresses !== null && tabCounts.addresses !== undefined) {
      <span class="side-badge">{{ tabCounts.addresses }}</span>
    }
  </a>
  <!--
    <a class="side-nav-link" [class.active]="activePanel === 'payments'" (click)="showPanel('payments')">
        <i class="bi bi-credit-card"></i> Payment Methods
    </a>
    -->
  <a
    class="side-nav-link"
    [class.active]="activePanel === 'notifications'"
    (click)="showPanel('notifications')"
  >
    <i class="bi bi-bell"></i> Notifications
    @if (
      tabCounts.notifications !== null && tabCounts.notifications !== undefined
    ) {
      <span class="side-badge">{{ tabCounts.notifications }}</span>
    }
  </a>
  <a
    class="side-nav-link"
    [class.active]="activePanel === 'password'"
    (click)="showPanel('password')"
  >
    <i class="bi bi-lock"></i> Password
  </a>
  <div class="side-divider"></div>
  <a class="side-nav-link" style="color: #dc3545" (click)="onSignOut()">
    <i class="bi bi-box-arrow-right"></i> Sign Out
  </a>
</div>
