// react-frontend/src/components/author-section/AuthorSection.tsx
import { useState, useEffect } from "react";
import { Link } from "react-router-dom";
import { getAllBooks } from "../../services/bookService";
import type { IBookSummary } from "../../types/book.types";
import { toSlug } from "../../utils/stringUtils";

interface AuthorSectionProps {
  name: string | null;
  bio: string | null;
  isFallback?: boolean;
  image: string | null;
  id: number | null;
}

export default function AuthorSection({
  name,
  bio,
  isFallback = false,
  image,
  id,
}: AuthorSectionProps) {
  const [authorBooks, setAuthorBooks] = useState<IBookSummary[]>([]);

  useEffect(() => {
    getAllBooks(name ?? undefined, 4, 1, undefined, undefined)
      .then((res) => setAuthorBooks(res.data.items))
      .catch(() => {
        // silently fail
      });
  }, [name]);

  return (
    <section className="section-py bg-warm">
      <div className="container">
        <div className="row align-items-center g-5">
          {/* Image */}
          <div className="col-lg-5">
            <div className="split-img">
              <Link to={`/author/${id}/${toSlug(name ?? "")}`}>
                <img src={image ?? undefined} alt={name ?? ""} loading="lazy" />
              </Link>
            </div>
          </div>

          {/* Content */}
          <div className="col-lg-7">
            <span className="section-label">
              {isFallback ? "Author Spotlight" : "Author of the Month"}
            </span>

            <h2 className="section-title mb-3">{name}</h2>
            <p className="text-brand-gray lh-lg mb-4">{bio}</p>

            <h6
              className="fw-bold mb-3"
              style={{ fontFamily: '"Lato", sans-serif' }}
            >
              Featured Works
            </h6>

            {authorBooks.map((book) => (
              <div
                key={book.id}
                className="d-flex align-items-center gap-3 py-3 border-bottom border-brand"
              >
                {book.image && (
                  <Link to={`/book/${book.id}/${toSlug(book.title)}`}>
                    <img
                      src={book.image}
                      alt={book.title}
                      className="rounded flex-shrink-0"
                      style={{ width: 48, height: 62, objectFit: "cover" }}
                    />
                  </Link>
                )}
                <span
                  className="fw-semibold flex-grow-1"
                  style={{ fontSize: "0.95rem" }}
                >
                  {book.title}
                </span>
                <span className="text-gold fw-bold small">{book.price}</span>
              </div>
            ))}

            <Link
              to={`/author/${id}/${toSlug(name ?? "")}`}
              className="btn btn-gold btn-lg px-5 text-uppercase fw-bold mt-4"
            >
              Read More
            </Link>
          </div>
        </div>
      </div>
    </section>
  );
}

// frontEnd/src/app/components/author-section/author-section.component.ts
import { Component, Input, OnInit, signal } from "@angular/core";
import { CommonModule } from "@angular/common";
import { ApiBookService } from "../../services/books/api-book.service";
import { map } from "rxjs";
import { RouterLink } from "@angular/router";
import { IBookSummary } from "../../models/Book/i-book-summary";

@Component({
  selector: "app-author-section",
  standalone: true,
  imports: [CommonModule, RouterLink],
  templateUrl: "./author-section.component.html",
})
export class AuthorSectionComponent implements OnInit {
  @Input() name!: string | null;
  @Input() bio!: string | null;
  @Input() IsFallBack? = false;
  @Input() image!: string | null;
  @Input() id!: number | null;
  //@Input() books!: any;

  authorBooks = signal<IBookSummary[]>([]);
  constructor(private apiBookSer: ApiBookService) {}

  ngOnInit() {
    this.apiBookSer
      .getAllBooks(this.name ?? undefined, 4, 1, undefined, undefined)
      .pipe(map((result) => result.items))
      .subscribe((books) => this.authorBooks.set(books));
  }

  toSlug(value: string) {
    return value
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "");
  }
}

<section class="section-py bg-warm">
  <div class="container">
    <div class="row align-items-center g-5">
      <!-- Image -->
      <div class="col-lg-5">
        <div class="split-img">
          <a [routerLink]="['/author', id, toSlug(name || '')]">
            <img [src]="image" [alt]="name" loading="lazy" />
          </a>
        </div>
      </div>

      <!-- Content -->
      <div class="col-lg-7">
        @if (IsFallBack) {
          <span class="section-label">Author Spotlight</span>
        } @else {
          <span class="section-label">Author of the Month</span>
        }
        <h2 class="section-title mb-3">{{ name }}</h2>
        <p class="text-brand-gray lh-lg mb-4">{{ bio }}</p>

        <h6
          class="fw-bold mb-3"
          style="font-family: &quot;Lato&quot;, sans-serif"
        >
          Featured Works
        </h6>

        @for (book of authorBooks(); track book.id) {
          <div
            class="d-flex align-items-center gap-3 py-3 border-bottom border-brand"
          >
            @if (book.image) {
              <a [routerLink]="['/book', book.id, toSlug(book.title)]">
                <img
                  [src]="book.image"
                  [alt]="book.title"
                  class="rounded flex-shrink-0"
                  style="width: 48px; height: 62px; object-fit: cover"
                />
              </a>
            }
            <span class="fw-semibold flex-grow-1" style="font-size: 0.95rem">{{
              book.title
            }}</span>
            <span class="text-gold fw-bold small">{{ book.price }}</span>
          </div>
        }

        <a
          [routerLink]="['/author', id, toSlug(name || '')]"
          class="btn btn-gold btn-lg px-5 text-uppercase fw-bold mt-4"
        >
          Read More
        </a>
      </div>
    </div>
  </div>
</section>
